hr_paragraphs.settings:
  type: config_object
  label: 'HR Paragraphs settings'
  mapping:
    fts_api_url:
      type: string
      label: 'FTS API URL'
    fts_api_key:
      type: string
      label: 'FTS API key'
    idps_api_url:
      type: string
      label: 'IDPs API URL'
    idps_api_key:
      type: string
      label: 'IDPs API key'
    rw_crisis_api_url:
      type: string
      label: 'RW Crisis API URL'
    rw_crisis_api_key:
      type: string
      label: 'RW Crisis API key'

field.widget.settings.hr_paragraphs_link_default:
  type: mapping
  label: 'Link format settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
