hr_paragraphs.settings:
  type: config_object
  label: 'HR Paragraphs settings'
  mapping:
    fts_api_url:
      type: string
      label: 'FTS API URL including authentication'

field.widget.settings.hr_paragraphs_link_default:
  type: mapping
  label: 'Link format settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
