_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  contextual: 0
  csp: 0
  ctools: 0
  datetime: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gnode: 0
  google_tag: 0
  group: 0
  help: 0
  hr_paragraphs: 0
  image: 0
  language: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  locale: 0
  maintenance200: 0
  memcache: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_routes: 0
  mysql: 0
  node: 0
  ocha_search: 0
  options: 0
  page_cache: 0
  paragraphs_group_permissions: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  select2: 0
  shortcut: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  subgroup: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  theme_switcher: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  user_expire: 0
  variationcache: 0
  views_ui: 0
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  formdazzle: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  seven: 0
  stable: 0
  common_design: 0
  common_design_subtheme: 0
  hri_admin: 0
profile: minimal
