_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 2c660645-429a-41a3-a911-cc3ccf2de31a
name: 'ReliefWeb Numbers'
mail: donotreply+numbers@reliefweb.int
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
