purge_on_cache_clear: false
storage: profiler.file_storage
exclude: '/admin/*'
active_toolbar_items:
  cache: cache
  config: config
  database: database
  devel: devel
  forms: forms
  http: http
  performance_timing: performance_timing
  request: request
  routing: routing
  services: services
  state: state
  time: time
  assets: '0'
  blocks: '0'
  events: '0'
  drupal_extension: '0'
  mail: '0'
  php_config: '0'
  theme: '0'
  translations: '0'
  user: '0'
  views: '0'
ide_link: ''
ide_link_remote: ''
ide_link_local: ''
query_sort: null
query_highlight: null
